version: '3.3'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: valerycode/foodgram:latest
    restart: always
    expose:
      - 8000
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ./dump.json:/code/dump.json
    depends_on:
      - db
    env_file:
      - /.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data: 
  static_value:
  media_value:
